# https://circleci.com/docs/2.1/language-javascript/
version: 2.1
orbs:
  codecov: codecov/codecov@3.2.2
jobs:
  'build':
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Setup env variables
          command: echo 'export CODECOV_TOKEN="8763da5d-2ec9-4bb7-8258-1eb230173fb9"' >> $BASH_ENV
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn test:unit:coverage
      - codecov/upload:
          file: coverage/coverage-final.json

workflows:
  version: 2
  build:
    jobs:
      - 'build'
